# Generated by Django 5.2.8 on 2025-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('rain', 'Rain'), ('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('windy', 'Windy'), ('storm', 'Storm'), ('fog', 'Fog'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
